blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>', views.PostDetailView.as_view(), name = 'detail'),


    path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),


]

blog/models.py
import markdown
from django.urls import reverse
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.utils.html import strip_tags


class Category(models.Model):
    """定义模型类
    分类
    """
    name = models.CharField('分类名',max_length=100)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    定义模型类
    标签名
    """
    name = models.CharField('标签名',max_length=100)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    模型类
    文章
    """
    # 文章标题
    title = models.CharField('标题', max_length=70)

    # 文章正文
    body = models.TextField('正文')

    # 文章创建时间
    created_time = models.DateTimeField('创建的时间', default=timezone.now)

    # 文章修改时间
    modified_time = models.DateTimeField('修改的时间')

    # 文章摘要
    excerpt = models.CharField('摘要', max_length=200, blank=True)

    # 文章外键（一对多）：分类名
    # 一篇文章只能对应一个分类名，一个分类中有多篇文章
    category = models.ForeignKey(Category,verbose_name='分类', on_delete=models.CASCADE)

    # 文章外键（多对多）：标签名
    # 一篇文章可以有多个标签，一个标签可以有多篇文章
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)

    # 文章外键（一对多）：作者
    # 一篇文章有只能有一个作者，一个作者可以有多篇文章
    author = models.ForeignKey(User,verbose_name='作者', on_delete=models.CASCADE)

    # 阅读量
    views = models.PositiveIntegerField(default=0, editable=False)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    # 定义函数__str__
    def __str__(self):
        return self.title

    # 定义函数save（）
    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()
        # 首先实例化一个 Markdown 类，用于渲染 body 的文本。
        # 由于摘要并不需要生成文章目录，所以去掉了目录拓展。
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        # 第一：先将 Markdown 文本渲染成 HTML 文本
        # 第二：strip_tags 去掉 HTML 文本的全部 HTML 标签
        # 第三：从文本摘取前 54 个字符赋给 excerpt
        self.excerpt = strip_tags(md.convert(self.body))[:0]
        super().save(*args, **kwargs)

    # 定义get_absolute_url()
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    # 定义函数increase_views（）
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

comments/models.py
from django.db import models
from django.utils import timezone


class Comment(models.Model):
    name = models.CharField('名字', max_length= 50)
    email = models.EmailField('邮箱')
    url = models.URLField('网址', blank= True)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间', default= timezone.now())
    post = models.ForeignKey('blog.Post', verbose_name='文章', on_delete= models.CASCADE)


    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{}:{}'.format(self.name, self.text[:20])

blog/views.py
import re

import markdown
from django.shortcuts import render, get_object_or_404
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from pure_pagination import PaginationMixin

from .models import Post, Category, Tag
from django.views.generic import ListView, DetailView


# def index(request):
#     """定义博客主页视图"""
#     post_list = Post.objects.all()#.order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})
# class IndexView(PaginationMixin, ListView):
class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 10



# def archive(request, year, month):
#     """定义 归档 视图"""
#     post_list = Post.objects.filter(created_time__year=year,
#                                     created_time__month=month
#                                     )#.order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})
class ArchiveView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super().get_queryset().filter(created_time__year=year, created_time__month=month)


# def category(request, pk):
#     """定义 分类 视图"""
#     # 记得在开始部分导入 Category 类
#     cate = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.filter(category=cate)#.order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})
class CategoryView(IndexView):
    # model = Post
    # template_name = 'blog/index.html'
    # context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(category=cate)


# def tag(request, pk):
#     # 记得在开始部分导入 Tag 类
#     t = get_object_or_404(Tag, pk=pk)
#     post_list = Post.objects.filter(tags=t)#.order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})
class TagView(IndexView):
    def get_queryset(self):
        t = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(tags=t)


# def detail(request, pk):
#     """定义文章详情页视图"""
#     post = get_object_or_404(Post, pk=pk)
#
#     #阅读量+1
#     post.increase_views()
#
#     md = markdown.Markdown(extensions=[
#         'markdown.extensions.extra',
#         'markdown.extensions.codehilite',
#         # 'markdown.extensions.toc',
#         # 记得在顶部引入 TocExtension 和 slugify
#         TocExtension(slugify=slugify),
#     ])
#     post.body = md.convert(post.body)
#
#     m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
#     post.toc = m.group(1) if m is not None else ''
#
#     return render(request, 'blog/detail.html', context={'post': post})
class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super().get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super().get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            # 记得在顶部引入 TocExtension 和 slugify
            TocExtension(slugify=slugify),
        ])
        post.body = md.convert(post.body)

        m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
        post.toc = m.group(1) if m is not None else ''

        return post

templates/blog/detail.html
{% extends 'base.html' %}
{% load comments_extras %}
    {% block main %}
        <article class="post post-{{post.pk}}">
            <header class="entry-header">
                <h1 class="entry-title">{{post.title}}</h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{post.category.name}}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{post.created_time}}">{{post.created_time}}</time></a></span>
                    <span class="post-author"><a href="#">{{post.author}}</a></span>
                    <span class="comments-link"><a href="#comment-area">{{ post.comment_set.count }}评论</a></span>
                    <span class="views-count"><a href="#">{{ post.views }}阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                {{post.body|safe}}
            </div>
        </article>
        <section class="comment-area" id="comment-area">
            <hr>
            <h3>发表评论</h3>
            {% show_comment_form post %}
            <div class="comment-list-panel">
                {% show_comments post %}
            </div>
        </section>
    {% endblock main%}

    {% block toc %}
      {% if post.toc %}
        <div class="widget widget-content">
          <h3 class="widget-title">文章目录</h3>
          <div class="toc">
            <ul>
              {{ post.toc|safe }}
            </ul>
          </div>
        </div>
      {% endif %}
    {% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}
    {% block main %}
        {% for post in post_list %}
        <article class="post post-{{post.pk}}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{post.get_absolute_url}}">{{ post.title }}</a>
                <div class="entry-meta">
                    <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{post.category.name}}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{post.created_time}}">{{post.created_time}}</time></a></span>
                    <span class="post-author"><a href="#">{{post.author}}</a></span>
                    <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }}评论</a></span>
                    <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }}阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{post.excerpt}}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{post.get_absolute_url}}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
        {% empty %}
            <div class="no-post">暂时没有发布的文章</div>
        {% endfor %}

        {% if is_paginated %}
        <div class="pagination-simple">
          <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
          {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
          {% endif %}
          <!-- 显示当前页面信息 -->
          <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
          <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
          {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">下一页</a>
          {% endif %}
        </div>
        {% endif %}

<!--        {% if is_paginated %}-->
<!--            {{ page_obj.render }}-->
<!--        {% endif %}-->

    {% endblock main%}